### ISSUE TITLE
Scaling overlaps and cuts text away

### ISSUE THREAD

**Issue by XLPhere** [CMDRVoltages/CMDRVoltages.github.io#2]
Text and icons may overlap or get cut away in some scenarios:
**Width <630**
Cuts away the text on the side
![image](https://user-images.githubusercontent.com/13018470/70938077-c64d2c00-2045-11ea-9df3-f9fd5ba307eb.png)
**Height <630**
Icons overlap with text
![image](https://user-images.githubusercontent.com/13018470/70938137-e250cd80-2045-11ea-88b5-41d4ad03eafa.png)

**Comment by CMDRVoltages** [comment]
@XLPhere The issue has been resolved. 
Please clear your cache and refresh the site.
